# Generated by Django 5.2.5 on 2025-09-12 02:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('incidencia', models.FloatField(help_text='Porcentaje de incidencia del espacio en el nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('incidencia', models.FloatField(help_text='Porcentaje de incidencia del nivel en el proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('superusuario', 'SuperUsuario'), ('superadmin_empresa', 'SuperAdministrador de empresa'), ('admin_empresa', 'Administrador de Empresa'), ('supervisor_constructor', 'Supervisor / Constructor'), ('calidad', 'Calidad')], default='superusuario', max_length=50)),
                ('cargo', models.CharField(blank=True, choices=[('programador_control_avance', 'Programador y control de avance'), ('admin_obra', 'Administrador de obra'), ('jefe_ot', 'Jefe de Oficina Técnica'), ('personal_calidad', 'Personal de Calidad'), ('jefe_terreno', 'Jefe de Terreno'), ('supervisor', 'Supervisores'), ('gerente_proyecto', 'Gerente de Proyecto')], max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('administrador_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_administradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='construccion1app.empresa'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('avance', models.FloatField(default=0.0, help_text='Porcentaje de avance de la actividad')),
                ('incidencia', models.DecimalField(decimal_places=2, help_text='Porcentaje de incidencia de la actividad en el espacio', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('estado_ejecucion', models.CharField(choices=[('no_ejecutada', 'No ejecutada'), ('ejecucion', 'En ejecución'), ('ejecutada', 'Ejecutada'), ('revisada', 'Revisada'), ('observada', 'Observada')], default='ejecucion', max_length=20)),
                ('estado_asignacion', models.CharField(choices=[('POR_ASIGNAR', 'Por asignar'), ('ASIGNADA', 'Asignada'), ('NO_ASIGNADA', 'No asignada')], default='POR_ASIGNAR', max_length=20)),
                ('foto', models.ImageField(blank=True, help_text='Subida por calidad', null=True, upload_to='actividades/fotos/')),
                ('justificacion', models.TextField(blank=True, help_text='Justificación subida', null=True)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha planificada de inicio de la actividad', null=True)),
                ('habilitada', models.BooleanField(default=True, help_text='Indica si la actividad está habilitada para ser ejecutada')),
                ('asignado', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'supervisor_constructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_asignadas', to=settings.AUTH_USER_MODEL)),
                ('predecesora', models.ForeignKey(blank=True, help_text='Actividad que debe completarse antes de iniciar esta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucesoras', to='construccion1app.actividad')),
                ('sucesora', models.ForeignKey(blank=True, help_text='Actividad que depende de esta para comenzar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predecesoras', to='construccion1app.actividad')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='construccion1app.espacio')),
            ],
        ),
        migrations.AddField(
            model_name='espacio',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='construccion1app.nivel'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construccion1app.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rubro', models.CharField(blank=True, choices=[('vivienda', 'Vivienda'), ('infraestructura', 'Infraestructura'), ('comercial', 'Comercial'), ('industrial', 'Industrial'), ('remodelacion', 'Remodelación'), ('urbanizacion', 'Urbanización'), ('obra_publica', 'Obra Pública'), ('otros', 'Otros')], max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, choices=[('arica', 'Arica y Parinacota'), ('tarapaca', 'Tarapacá'), ('antofagasta', 'Antofagasta'), ('atacama', 'Atacama'), ('coquimbo', 'Coquimbo'), ('valparaiso', 'Valparaíso'), ('metropolitana', 'Metropolitana de Santiago'), ('ohiggins', "Libertador Gral. Bernardo O'Higgins"), ('maule', 'Maule'), ('nuble', 'Ñuble'), ('biobio', 'Biobío'), ('araucania', 'La Araucanía'), ('rios', 'Los Ríos'), ('lagos', 'Los Lagos'), ('aysen', 'Aysén del Gral. Carlos Ibáñez del Campo'), ('magallanes', 'Magallanes y de la Antártica Chilena')], max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='construccion1app.empresa')),
                ('usuarios_acceso', models.ManyToManyField(blank=True, related_name='proyectos_acceso', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nivel',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='construccion1app.proyecto'),
        ),
    ]
