# Generated by Django 5.2.5 on 2025-11-27 23:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion1app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='foto',
        ),
        migrations.AddField(
            model_name='actividad',
            name='aprobacion_calidad',
            field=models.BooleanField(default=True, help_text='Indica si la actividad requiere aprobación de calidad'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='archivo_informacion',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Archivo con información adicional para la actividad', max_length=255, null=True, verbose_name='informacion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='archivo_justificacion',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Archivo de justificación subida', max_length=255, null=True, verbose_name='justificacion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha planificada de fin de la actividad', null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='information',
            field=models.BooleanField(default=False, help_text='Indica si la actividad requiere información adicional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='habilitada',
            field=models.BooleanField(default=False, help_text='Indica si la actividad está habilitada para ser ejecutada'),
        ),
    ]
