# Generated by Django 5.2.5 on 2025-09-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='habilitada',
            field=models.BooleanField(default=False, help_text='Indica si la actividad está habilitada para ser ejecutada'),
        ),
    ]
