# Generated by Django 5.2.5 on 2025-10-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion1app', '0002_alter_actividad_habilitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='aprobacion_calidad',
            field=models.BooleanField(default=True, help_text='Indica si la actividad requiere aprobación de calidad'),
        ),
    ]
