# Generated by Django 5.2.5 on 2025-10-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion1app', '0003_actividad_aprobacion_calidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha planificada de fin de la actividad', null=True),
        ),
    ]
