# Generated by Django 5.2.5 on 2025-10-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion1app', '0004_actividad_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='foto',
        ),
        migrations.AddField(
            model_name='actividad',
            name='archivo_informacion',
            field=models.FileField(blank=True, help_text='Archivo con información adicional para la actividad', null=True, upload_to='actividades/informacion_adicional/'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='archivo_justificacion',
            field=models.FileField(blank=True, help_text='Archivo de justificación subida', null=True, upload_to='actividades/justificaciones/'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='information',
            field=models.BooleanField(default=False, help_text='Indica si la actividad requiere información adicional'),
        ),
    ]
