# Generated by Django 5.2.5 on 2025-11-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construccion1app', '0005_remove_actividad_foto_actividad_archivo_informacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
