"""
Django settings for construccion1 project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os 
import django_heroku
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+bfs32#558dz+8^9@pjjc78j@t(c9ug@r6cnzx5qn%ab5^5*7@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
LOGIN_REDIRECT_URL = '/mis-proyectos/'  
LOGIN_URL = '/login/'  # URL del login
LOGOUT_REDIRECT_URL = '/logout/'  # Redirige al logout

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5','construccion1app.apps',
    'construccion1app.apps.Construccion1AppConfig', 
    
    'webpush',
    'pwa', # ✅ solo esta
]


WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIEwQp7Px3CXNXeVnoom0nciRstnZdgbJMnc3mpKp8FEDumis3tMBZktm12ALsfNg5UOIVHPJvkpOQzadfqZHcw==",
    "VAPID_PRIVATE_KEY": "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg956qitn6Ou-OGLjkhoqbbqufRYf9giiWbfO6PFbKaTShRANCAAQgTBCns_HcJc1d5WeiibSdyJGy2dl2BskydzeakqnwUQO6aKze0wFmS2bXYAux82DlQ4hUc8m-Sk5DNp1-pkdz",
    "VAPID_ADMIN_EMAIL": "andres.luarte@luartech.cl"
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# settings.py
TIME_ZONE = 'America/Santiago'
USE_TZ = True   # recomendable dejarlo en True

ROOT_URLCONF = 'construccion1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'construccion1app.context_processors.notificaciones_context',
                'construccion1app.context_processors.webpush_settings',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'construccion1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'construccion1bd',
#        'USER': 'postgres',
#        'PASSWORD': 'postgres',
#        'HOST': 'localhost',
#        'PORT': '5432',
#   }
#}



# Configuración de base de datos
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://u8pergpsrneqj9:p7a766b1364f8ec48ad7cf5f1d3e5064d577cd112c1251f3c5aeeaedded59d3b3@cee3ebbhveeob.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d7geplabfju1gr',
        conn_max_age=600
    )
}
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

#DATABASES = {
#   'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#       'NAME': 'd7geplabfju1gr',
#        'USER': 'u8pergpsrneqj9',
#        'PASSWORD': 'p7a766b1364f8ec48ad7cf5f1d3e5064d577cd112c1251f3c5aeeaedded59d3b3',
#        'HOST': 'cee3ebbhveeob.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com',
#       'PORT': '5432',
#    }
#}

AUTH_USER_MODEL = 'construccion1app.Usuario'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
ALLOWED_HOSTS = ['.herokuapp.com', 'localhost', '127.0.0.1']
MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# === Rutas base del proyecto ===
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# === Idioma y zona horaria ===
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# === Archivos estáticos (CSS, JS, imágenes) ===
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 📁 carpeta donde Django recopila los estáticos para producción
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')  # 📂 carpeta donde guardas tus archivos estáticos locales (en desarrollo)
]

# === Archivos multimedia (subidas de usuario, imágenes, PDFs, etc.) ===
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 📂 carpeta donde se guardan archivos subidos por usuarios

# === Configuración adicional ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
X_FRAME_OPTIONS = 'SAMEORIGIN'

# === Progressive Web App (PWA) ===
PWA_APP_NAME = 'ConstruApp'
PWA_APP_DESCRIPTION = "Control Planner para obras"
PWA_APP_THEME_COLOR = '#0a1f44'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {'src': '/static/construccion1app/img/logo2.jpeg', 'sizes': '512x512'}
]
PWA_APP_ICONS_APPLE = [
    {'src': '/static/construccion1app/img/logo2.jpeg', 'sizes': '512x512'}
]
PWA_APP_SPLASH_SCREEN = [
    {'src': '/static/construccion1app/img/logo2.jpeg', 'media': '(prefers-color-scheme: light)'}
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es-ES'

# === Integración con Heroku ===
django_heroku.settings(locals())
